spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
