spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092
